### ISSUE TITLE
Support for DialogFlow Intent Name Limit

### ISSUE THREAD

**Issue by NikV** [Botmock/botmock-dialogflow-export#37]
**Overview**
For interest it seems Dialogflow has a limit to length of intent names: Errors in project-qr_i_value_stmts_dont_agree_final_sure-qr_i_value_stmts_dont_agree_still_disagree_ok-quick-...' intent: Name length is greater than 100 chars.

**To Reproduce**
TBD

**Expected behavior**

**Screenshots**
DialogFlow should work as usual and not throw an error about Intent Name Lengths. 

**Additional context**
N/A

**Comment by reyerm** [comment]
I think this has been addressed now? seemed to work fine

**Comment by nonnontrivial** [comment]
@reyerm correct. Should be fixed as of https://github.com/Botmock/botmock-dialogflow-export/pull/30
