### ISSUE TITLE
Images trigger error on import

### ISSUE THREAD

**Issue by NikV** [Botmock/botmock-dialogflow-export#38]
**Overview**
It seems it that DialogFlow is not able to handle carousel / card types, probably because of the slash in the name of the item in Botmock. is so, probably a simple fix to replace the character that is causing the issue.

**To Reproduce**
1. Add a card or carousel in a Botmock Flow
2. Use Export Script 
3. Try to add zip to DialogFlow, and an error should show up. 

TBD

**Expected behavior**
Slash character in some message types should not break the exporter and Images should be handled correctly in projects that map to “Generic”.

**Additional context**
N/A

**Comment by reyerm** [comment]
To clarify overview (is in your title but not in overview), it also does not handle images in the export.
To reproduce, should be a simple matter of :
Create image as a step in in Botmock flow
export to Dialogflow format
Try to import into Dialogflow, should get an error from import functionality.

**Comment by NikV** [comment]
@reyerm Thanks! Meant to clarify it a bit better in the ticket, and will update the ticket to reflect the steps to reproduce too 👍

**Comment by NikV** [comment]
@reyerm We’re actually moving to switch the image issue into a different issue: https://github.com/Botmock/botmock-dialogflow-export/issues/42

Feel free to follow along there for a more organized look into the image issue, which may require a different solution/workaround.

**Comment by nonnontrivial** [comment]
Closing now that https://github.com/Botmock/botmock-dialogflow-export/pull/79 has landed.
