### ISSUE TITLE
Image Block Support

### ISSUE THREAD

**Issue by NikV** [Botmock/botmock-dialogflow-export#42]
**Overview**
In Botmock, when a project with an image block is imported into DialogFlow, it immediately shows an error.

**To Reproduce**
1. Add an image in Botmock 
2. Use Script 
3. Try to add script to DialogFlow, and an error should show up. 

TBD

**Expected behavior**
In DialogFlow, an image should load properly when it is imported from a Botmock Flow.

**Additional context**
N/A

**Comment by nonnontrivial** [comment]
Closing in favor of #46
