### ISSUE TITLE
Generic: Card type has no "buttons" property

### ISSUE THREAD

**Issue by dawidjaniga** [Botmock/botmock-dialogflow-export#48]
**Issue Overview**
When exporting conversational flow, on elements which have type [*card* ](https://github.com/Botmock/botmock-dialogflow-export/blob/master/lib/providers/Generic.js#L6) error occurs:

```
(node:36475) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined
    at Generic.card (/botmock/lib/providers/Generic.js:7:34)
    at Provider.create (/botmock/lib/providers/index.ts:59:31)
    at /botmock/index.ts:363:34
    at Array.map (<anonymous>)
    at /botmock/index.ts:362:24
```

Data causing error passed to card method:
```
{
  nodeName: 'Trip options',
  elements: [
    {
      title: 'Title',
      image_url: 'https://botmock.s3.amazonaws.com/image.jpg',
      buttons: [
        {
          content_type: 'text',
          title: '',
          payload: '',
          context: [ [length]: 0 ]
        },
        [length]: 1
      ]
    },
    [length]: 1
  ],
  text: 'Get Started Text'
}
```

**To Reproduce**
1. Create conversational flow
2. Add element *Crousel/Card* with image and title only
3. Configure .env and export flow via npm start

**Expected behavior**
Exported flow to output dir.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - NPM Version: 6.10.3
 - Node: 12.8.0

**Comment by nonnontrivial** [comment]
Thank you @dawidjaniga ! A fix for this is included in #49

**Comment by dawidjaniga** [comment]
Thanks @nonnontrivial, that's was fast 🙇 :D

**Comment by dawidjaniga** [comment]
Guys, I would like re-open the issue. `data.elements` are working now, but the same error as above occurs for `data.buttons`. What do you think about unit testing?

**Comment by nonnontrivial** [comment]
Sure @dawidjaniga . Can you expand on the problem? Unit testing (and integration testing) is something we are very interested in adding.

**Comment by dawidjaniga** [comment]
The deleted code was responsible for handling `data.buttons` and now problem with that property occurs. The raw idea might be:
```
card (data) {
    let buttons = []
    
    if (data.elements) {
      buttons = data.elements.flatMap(element =>
        element.buttons.reduce((acc, button) => {
          return [...acc, { text: button.title, postback: button.payload }]
        }, [])
      )
    } else if (data.buttons) {
      buttons = data.buttons.map(button => ({
        text: button.title,
        postback: button.payload,
      }));  
    }
    
    return { type: 1, title: data.text, buttons }
  }
```

Unit testing can protect from situation like that.

**Comment by nonnontrivial** [comment]
Thanks @dawidjaniga . Opened https://github.com/Botmock/botmock-dialogflow-export/pull/51 for this.
