### ISSUE TITLE
Slack Links Are Not Properly Exported

### ISSUE THREAD

**Issue by NikV** [Botmock/botmock-dialogflow-export#56]
**Issue Overview**
In this issue, Links that are created in Slack attachments are not being set and exported properly when trying to go from Botmock->DialogFlow.

**To Reproduce**
1. Setup a "Link" in the Attachments in Slack
2. Try to Export to DialogFlow
3. In DialogFlow, you will not be able to see the links added in the message attachment.

**Expected behavior**
That Links work and are acknowledged by DialogFlow using the export script.

**Additional Context**
N/A

**Comment by nonnontrivial** [comment]
@NikV can you clarify what you mean by "link"?
