### ISSUE TITLE
Export doesn't copy the right language

### ISSUE THREAD

**Issue by LukeJanissen** [Botmock/botmock-dialogflow-export#77]
I created a project in Botmock in Dutch (Including setting the project to Dutch). But the export sets all the intents to English. So in my Dutch Dialogflow project, it only shows the responses if I set it to English. I don't know if this only happens with the Dutch Language, or also with other non-english languages.

` "messages": [
        {
          "speech": "Hallo, welkom.",
          "type": 0,
          "lang": "en",
          "condition": ""
        },
        {
          "speech": "Waar kan ik u mee helpen?",
          "type": 0,
          "lang": "en", //// this should be "nl"
          "condition": ""
        }
      ],`

**Comment by obaid** [comment]
Thanks for reporting the issue @LukeJanissen. We will investigate it shortly and update the ticket accordingly.
